### ISSUE TITLE
there is a 403 Forbidden error, wherne i run :    docker-compose up -d nginx app_1

### ISSUE THREAD

**Issue by cnipr** [flavienbwk/nginx-keycloak#7]
Thank you for generously sharing your code. I have a question that I need to consult with you. Could you please help me answer it? Thank you very much.

wherne i run :    docker-compose up -d nginx app_1

error info : 

[+] Running 0/1
 - nginx Warning                                                                                                                                                            1.7s
[+] Building 0.2s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                        0.0s
 => => transferring dockerfile: 277B                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                           0.1s
 => => transferring context: 2B                                                                                                                                             0.0s
 => ERROR [internal] load metadata for docker.io/openresty/openresty:1.21.4.1-8-alpine-fat                                                                                  0.1s
------
 > [internal] load metadata for docker.io/openresty/openresty:1.21.4.1-8-alpine-fat:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 1.21.4.1-8-alpine-fat]: 403 Forbidden

**Comment by cnipr** [comment]
it has been fixed after i restart the docker server

**Comment by flavienbwk** [comment]
Thank you for your feedback! I'm closing this issue as you were able to solve it.
